// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using histopat_back.Data;

#nullable disable

namespace histopat_back.Migrations
{
    [DbContext(typeof(HistopatDbContext))]
    [Migration("20251027221759_AddDescriptionToModuleAndSubtopic")]
    partial class AddDescriptionToModuleAndSubtopic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("histopat_back.Models.Module.ModuleHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("IdModule")
                        .HasColumnType("INT");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("IdModule");

                    b.HasIndex("IdUser");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleHistories", (string)null);
                });

            modelBuilder.Entity("histopat_back.Models.Module.ModuleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModuleModelId")
                        .HasColumnType("INT");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModuleModelId");

                    b.ToTable("ModuleImage");
                });

            modelBuilder.Entity("histopat_back.Models.Module.ModuleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("histopat_back.Models.Slide.SlideHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSlide")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSlide");

                    b.HasIndex("IdUser");

                    b.ToTable("SlideHistory");
                });

            modelBuilder.Entity("histopat_back.Models.Slide.SlideModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSubTopico")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdSubTopico");

                    b.ToTable("Slide");
                });

            modelBuilder.Entity("histopat_back.Models.Subtopic.SubTopicHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSubTopic")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSubTopic");

                    b.HasIndex("IdUser");

                    b.ToTable("SubTopicHistory");
                });

            modelBuilder.Entity("histopat_back.Models.Subtopic.SubtopicModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTopic")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTopic");

                    b.ToTable("SubTopic");
                });

            modelBuilder.Entity("histopat_back.Models.Topic.TopicHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTopic")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTopic");

                    b.HasIndex("IdUser");

                    b.ToTable("TopicHistory");
                });

            modelBuilder.Entity("histopat_back.Models.Topic.TopicModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdModule")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdModule");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("histopat_back.Models.User.Role", b =>
                {
                    b.Property<byte>("IdRoles")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRoles");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("histopat_back.Models.User.UserModel", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("histopat_back.Models.User.UserRole", b =>
                {
                    b.Property<int>("IdUserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserRole"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<byte>("IdRoles")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdUserRole");

                    b.HasIndex("IdRoles");

                    b.HasIndex("IdUser");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("histopat_back.Models.Module.ModuleHistory", b =>
                {
                    b.HasOne("histopat_back.Models.Module.ModuleModel", null)
                        .WithMany("History")
                        .HasForeignKey("IdModule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User.UserModel", "User")
                        .WithMany("ModuleHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.Module.ModuleModel", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Module.ModuleImage", b =>
                {
                    b.HasOne("histopat_back.Models.Module.ModuleModel", null)
                        .WithMany("ModuleImages")
                        .HasForeignKey("ModuleModelId");
                });

            modelBuilder.Entity("histopat_back.Models.Slide.SlideHistory", b =>
                {
                    b.HasOne("histopat_back.Models.Slide.SlideModel", "Slide")
                        .WithMany("History")
                        .HasForeignKey("IdSlide")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User.UserModel", "User")
                        .WithMany("SlideHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slide");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Slide.SlideModel", b =>
                {
                    b.HasOne("histopat_back.Models.Subtopic.SubtopicModel", "SubTopic")
                        .WithMany("Slides")
                        .HasForeignKey("IdSubTopico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTopic");
                });

            modelBuilder.Entity("histopat_back.Models.Subtopic.SubTopicHistory", b =>
                {
                    b.HasOne("histopat_back.Models.Subtopic.SubtopicModel", "Subtopic")
                        .WithMany("History")
                        .HasForeignKey("IdSubTopic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User.UserModel", "User")
                        .WithMany("SubTopicHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Subtopic.SubtopicModel", b =>
                {
                    b.HasOne("histopat_back.Models.Topic.TopicModel", "Topic")
                        .WithMany("SubTopics")
                        .HasForeignKey("IdTopic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("histopat_back.Models.Topic.TopicHistory", b =>
                {
                    b.HasOne("histopat_back.Models.Topic.TopicModel", "Topic")
                        .WithMany("History")
                        .HasForeignKey("IdTopic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User.UserModel", "User")
                        .WithMany("TopicHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Topic.TopicModel", b =>
                {
                    b.HasOne("histopat_back.Models.Module.ModuleModel", "Module")
                        .WithMany("Topics")
                        .HasForeignKey("IdModule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("histopat_back.Models.User.UserRole", b =>
                {
                    b.HasOne("histopat_back.Models.User.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdRoles")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User.UserModel", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Module.ModuleModel", b =>
                {
                    b.Navigation("History");

                    b.Navigation("ModuleImages");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("histopat_back.Models.Slide.SlideModel", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("histopat_back.Models.Subtopic.SubtopicModel", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Slides");
                });

            modelBuilder.Entity("histopat_back.Models.Topic.TopicModel", b =>
                {
                    b.Navigation("History");

                    b.Navigation("SubTopics");
                });

            modelBuilder.Entity("histopat_back.Models.User.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("histopat_back.Models.User.UserModel", b =>
                {
                    b.Navigation("ModuleHistories");

                    b.Navigation("SlideHistories");

                    b.Navigation("SubTopicHistories");

                    b.Navigation("TopicHistories");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
