// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using histopat_back.Data;

#nullable disable

namespace histopat_back.Migrations
{
    [DbContext(typeof(HistopatDbContext))]
    partial class HistopatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("histopat_back.Models.Module", b =>
                {
                    b.Property<long>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdModule"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModule");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("histopat_back.Models.ModuleHistory", b =>
                {
                    b.Property<long>("IdModuleHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdModuleHistory"));

                    b.Property<long>("IdModule")
                        .HasColumnType("BIGINT");

                    b.Property<long>("IdUser")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModuleHistory");

                    b.HasIndex("IdModule");

                    b.HasIndex("IdUser");

                    b.ToTable("ModuleHistory");
                });

            modelBuilder.Entity("histopat_back.Models.Role", b =>
                {
                    b.Property<byte>("IdRoles")
                        .HasColumnType("TINYINT");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRoles");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("histopat_back.Models.Slide", b =>
                {
                    b.Property<long>("IdSlide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSlide"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdSubTopico")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSlide");

                    b.HasIndex("IdSubTopico");

                    b.ToTable("Slide");
                });

            modelBuilder.Entity("histopat_back.Models.SlideHistory", b =>
                {
                    b.Property<long>("IdSlideSubTopicHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSlideSubTopicHistory"));

                    b.Property<long>("IdSlide")
                        .HasColumnType("BIGINT");

                    b.Property<long>("IdUser")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSlideSubTopicHistory");

                    b.HasIndex("IdSlide");

                    b.HasIndex("IdUser");

                    b.ToTable("SlideHistory");
                });

            modelBuilder.Entity("histopat_back.Models.SubTopic", b =>
                {
                    b.Property<long>("IdSubTopico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSubTopico"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<long>("IdTopic")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DATETIME");

                    b.HasKey("IdSubTopico");

                    b.HasIndex("IdTopic");

                    b.ToTable("SubTopic");
                });

            modelBuilder.Entity("histopat_back.Models.SubTopicHistory", b =>
                {
                    b.Property<long>("IdSubTopicHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSubTopicHistory"));

                    b.Property<long>("IdSubTopico")
                        .HasColumnType("BIGINT");

                    b.Property<long>("IdUser")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSubTopicHistory");

                    b.HasIndex("IdSubTopico");

                    b.HasIndex("IdUser");

                    b.ToTable("SubTopicHistory");
                });

            modelBuilder.Entity("histopat_back.Models.Topic", b =>
                {
                    b.Property<long>("IdTopico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTopico"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<long>("IdModule")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTopico");

                    b.HasIndex("IdModule");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("histopat_back.Models.TopicHistory", b =>
                {
                    b.Property<long>("IdTopicHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTopicHistory"));

                    b.Property<long>("IdTopico")
                        .HasColumnType("BIGINT");

                    b.Property<long>("IdUser")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTopicHistory");

                    b.HasIndex("IdTopico");

                    b.HasIndex("IdUser");

                    b.ToTable("TopicHistory");
                });

            modelBuilder.Entity("histopat_back.Models.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUser"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("histopat_back.Models.UserRole", b =>
                {
                    b.Property<long>("IdUser")
                        .HasColumnType("BIGINT");

                    b.Property<byte>("IdRoles")
                        .HasColumnType("TINYINT");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.HasKey("IdUser", "IdRoles");

                    b.HasIndex("IdRoles");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("histopat_back.Models.ModuleHistory", b =>
                {
                    b.HasOne("histopat_back.Models.Module", "Module")
                        .WithMany("ModuleHistories")
                        .HasForeignKey("IdModule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User", "User")
                        .WithMany("ModuleHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Slide", b =>
                {
                    b.HasOne("histopat_back.Models.SubTopic", "SubTopic")
                        .WithMany("Slides")
                        .HasForeignKey("IdSubTopico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTopic");
                });

            modelBuilder.Entity("histopat_back.Models.SlideHistory", b =>
                {
                    b.HasOne("histopat_back.Models.Slide", "Slide")
                        .WithMany("SlideHistories")
                        .HasForeignKey("IdSlide")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User", "User")
                        .WithMany("SlideHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Slide");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.SubTopic", b =>
                {
                    b.HasOne("histopat_back.Models.Topic", "Topic")
                        .WithMany("SubTopics")
                        .HasForeignKey("IdTopic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("histopat_back.Models.SubTopicHistory", b =>
                {
                    b.HasOne("histopat_back.Models.SubTopic", "SubTopic")
                        .WithMany("SubTopicHistories")
                        .HasForeignKey("IdSubTopico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User", "User")
                        .WithMany("SubTopicHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Topic", b =>
                {
                    b.HasOne("histopat_back.Models.Module", "Module")
                        .WithMany("Topics")
                        .HasForeignKey("IdModule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("histopat_back.Models.TopicHistory", b =>
                {
                    b.HasOne("histopat_back.Models.Topic", "Topic")
                        .WithMany("TopicHistories")
                        .HasForeignKey("IdTopico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User", "User")
                        .WithMany("TopicHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.UserRole", b =>
                {
                    b.HasOne("histopat_back.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdRoles")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("histopat_back.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("histopat_back.Models.Module", b =>
                {
                    b.Navigation("ModuleHistories");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("histopat_back.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("histopat_back.Models.Slide", b =>
                {
                    b.Navigation("SlideHistories");
                });

            modelBuilder.Entity("histopat_back.Models.SubTopic", b =>
                {
                    b.Navigation("Slides");

                    b.Navigation("SubTopicHistories");
                });

            modelBuilder.Entity("histopat_back.Models.Topic", b =>
                {
                    b.Navigation("SubTopics");

                    b.Navigation("TopicHistories");
                });

            modelBuilder.Entity("histopat_back.Models.User", b =>
                {
                    b.Navigation("ModuleHistories");

                    b.Navigation("SlideHistories");

                    b.Navigation("SubTopicHistories");

                    b.Navigation("TopicHistories");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
